name: video_js_themed
description: Video Library for Flutter, Easily use video.js in flutter web with themes support
version: 0.0.6+2
homepage: https://github.com/PROGrand/video_js
issue_tracker: https://github.com/PROGrand/video_js/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  universal_html: ^2.0.8

  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ViewFactoryWeb
        fileName: web/register_view_factory.dart
